### ISSUE TITLE
Loading pre-trained DNN model using OpenVINO with Go & GoCV - symbol lookup error

### ISSUE THREAD

**Issue by JovanaKostic** [hybridgroup/gocv#493] opened 2019-08-10 15:31 UTC
I have installed, and verified installation of **OpenVINO** by following instructions at this link: https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux.html

Editor and Technologies that I am using are: **Visual Studio Code**, **Go Programming Language** and **AWS Lambda**

I am trying to load a pre-trained Deep Learning model and its configuration: **frozen_inference_graph.bin**, **frozen_inference_graph.xml**

Here is the code for it:

                        net := gocv.ReadNet(localModelPath, localModelConfigPath)
    			if net.Empty() {
    				glog.Errorf("Error occurred while trying to read DNN model and its configuration from %v. Error message - %v", localModelPath, err)
    				return err
    			}
    
    			defer net.Close()
    			net.SetPreferableBackend(gocv.NetBackendDefault)
    			net.SetPreferableTarget(gocv.NetTargetCPU)

Whenever I try to debug the program, after trying to execute **gocv.ReadNet** function I get the following error message:

    /home/jovana/go/src/pipeline/lambda/inferenceLambda/__debug_bin: symbol lookup error: /home/jovana/go/src/pipeline/lambda/inferenceLambda/__debug_bin: undefined symbol: _ZN2cv3dnn14dnn4_v201901227readNetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_

Note that **go/src/pipeline/lambda/inferenceLambda** is path to the main.go script I am trying to debug.

When I try just to run **main.go** script I get:

    /tmp/go-build091433297/b001/exe/main: symbol lookup error: /tmp/go-build091433297/b001/exe/main: undefined symbol: _ZN2cv3dnn14dnn4_v201901227readNetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_

I honestly have no idea what this message means and where to start fixing it. Please help.
* Operating System and version: Ubuntu 18.04
* OpenCV version used: 4.00
* How did you install OpenCV? With the information you provided at README.md
* GoCV version used:  latest
* Go version:go1.12 linux/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? It is automatically ran by following instructions at: https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux.html

**Comment by deadprogram** [comment] 2019-08-14 17:55
Please see https://github.com/hybridgroup/gocv/issues/491 as this is a duplicate of that issue.

Now closing. Thanks!

**Closed by deadprogram** 2019-08-14 17:55 UTC
Labels: duplicate
