### ISSUE TITLE
Maybe a bug of method GetUnconnectedOutLayers  in dnn.go

### ISSUE THREAD

**Issue by hawkwzh** [hybridgroup/gocv#542] opened 2019-11-14 01:19 UTC
I think there is a  bug ... 
Please check it.

gocv/dnn.go:405  
`pcids := *(*[]int)(unsafe.Pointer(h))`
Maybe it should be changed to 
`pcids := *(*[]C.int)(unsafe.Pointer(h))`

it make method [GetUnconnectedOutLayers()](https://github.com/hybridgroup/gocv/blob/b18291665d630fc258d89794f103190d4e213e72/dnn.go#L396) return an indeterminate result. It is RAM addr or not？

Please check it . Thx

**Comment by hawkwzh** [comment] 2019-11-26 10:14
nobody reply this？

**Comment by deadprogram** [comment] 2019-12-20 07:14
Hi @hawkwzh can you please provide a specific test case so we can reproduce it? Thank you.

**Comment by hawkwzh** [comment] 2019-12-23 03:42
@deadprogram I want to use darknet yolov3 to detect object. Just try it, will be reproduced. And it can be solved  with my solution. 
Then I try to retrieve my code for this comment.
Thx.

**Comment by hawkwzh** [comment] 2019-12-24 05:26
@deadprogram Oh , I made a mistake.
 gocv/dnn.go:162  is right.
I have re edited comments.

But ,I'm sure gocv/dnn.go:405 should be`pcids := *(*[]C.int)(unsafe.Pointer(h))`.
because incorrect result of `net.GetUnconnectedOutLayers()`method call  when using darknet(yolov3) to detecting.

**Comment by hawkwzh** [comment] 2019-12-24 08:39
@deadprogram 
Well.. I try to use tensorflow object detection.
[TensorFlow Object Detection](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API)
like this 
`net := gocv.ReadNet(weights, config)`
`names := net.GetUnconnectedOutLayersNames()`
I want to read the layer names, but result is :  
`"detection_out_finalHD�z��vs��n...+2305843009231782000 more"`

"detection_out_final" is right layer name.

use Model:[weights](http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2018_01_28.tar.gz)
use Config:[config](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/faster_rcnn_inception_v2_coco_2018_01_28.pbtxt)

please check it .
Thx.

**Comment by rengglian** [comment] 2019-12-28 23:27
I have the same issue as @hawkwzh describes. 
I fail to get gocv running with YOLO V3.

`func (net *Net) GetUnconnectedOutLayers() (ids []int)`

returns wrong ids.

I compared the result with [YOLO C++ OpenCV Tutorial](https://docs.opencv.org/master/da/d9d/tutorial_dnn_yolo.html)

[Source](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp)
Line 324 `static std::vector<int> outLayers = net.getUnconnectedOutLayers();`

gocv returns: [974957576392 254 0]
opencv demo: [200 227 254]

**Comment by intgogo** [comment] 2020-03-09 08:17
**My solution:**
```
func (net *Net) GetUnconnectedOutLayers() (ids []int) {
	cids := C.IntVector{}
	C.Net_GetUnconnectedOutLayers((C.Net)(net.p), &cids)
	defer C.free(unsafe.Pointer(cids.val))

	h := &reflect.SliceHeader{
		Data: uintptr(unsafe.Pointer(cids.val)),
		Len:  int(cids.length),
		Cap:  int(cids.length),
	}
	pcids := *(*[]C.int)(unsafe.Pointer(h))

	for i := 0; i < int(cids.length); i++ {
		ids = append(ids, int(pcids[i]))
	}
	return
}

func (net *Net) GetLayerNames() (names []string) {
	cstrs := C.CStrings{}
	C.Net_GetLayerNames((C.Net)(net.p), &cstrs)
	defer C.free(unsafe.Pointer(cstrs.strs))

	h := &reflect.SliceHeader{
		Data: uintptr(unsafe.Pointer(cstrs.strs)),
		Len:  int(cstrs.length),
		Cap:  int(cstrs.length),
	}
	pcstrs := *(*[](*C.char))(unsafe.Pointer(h))

	for i := 0; i < int(cstrs.length); i++ {
		names = append(names, C.GoString(pcstrs[i]))
	}
	return
}
```

**Comment by mngaonkar** [comment] 2020-06-13 19:46
I also encountered the same issue as described by @hawkwzh  with yolov3 and OpenCV 4.3, changing the code as follows fixed the issue for me as well.

pcids := \*(\*[]C.int)(unsafe.Pointer(h))

**Comment by freckie** [comment] 2020-09-08 09:51
I have the same issue and @intgogo 's solution works for me. Is there no one to make a PR?

**Comment by deadprogram** [comment] 2020-09-08 17:56
This was fixed by https://github.com/hybridgroup/gocv/pull/732 and is now in the `dev` branch so I will mark as "next-release".

**Comment by deadprogram** [comment] 2020-10-22 07:18
This has now been released so closing. Thanks!

**Closed by deadprogram** 2020-10-22 07:18 UTC
Labels: Next Release, bug
