### ISSUE TITLE
exit status 3221225781

### ISSUE THREAD

**Issue by HongyanJiao** [hybridgroup/gocv#362] opened 2018-11-24 11:38 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version:
* OpenCV version used:
* How did you install OpenCV?
* GoCV version used:
* Go version:
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by HongyanJiao** [comment] 2018-11-24 11:40
go version： go1.11 windows/amd64<br />MinGW:gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0<br />when I use cgo with dll, I got: exit status 3221225781

**Comment by HongyanJiao** [comment] 2018-11-24 11:42
`package main
// #cgo CFLAGS: -I./test
// #cgo LDFLAGS: -L./test -lTree
// #include "Tree.h"
import "C"
import 	"fmt"

func main() {
	fmt.Println("hello word")
	var x C.struct_Tree
	C.PrintHello(&x)
}`

**Comment by nekketsuuu** [comment] 2018-11-27 05:50
duplicate of #276?

**Closed** 2018-11-27 06:03 UTC

**Comment by HongyanJiao** [comment] 2018-11-27 06:04
> duplicate of #276?

I solved that problem, thank you
