### ISSUE TITLE
VSCode editor is invoking cc1plus process every intellisense activation for gocv

### ISSUE THREAD

**Issue by jcbritobr** [hybridgroup/gocv#18] opened 2017-10-27 01:49 UTC
All editors and ides using go tooling stop working with gocv installed. A process of cc1plus is spawned  at every intellisense activation and slowing down entire machine.

This happens on linux ubuntu 16.04 x86_64
![screenshot](https://user-images.githubusercontent.com/6579862/32084494-3a1e6514-baa8-11e7-8809-5f3d537af99a.png)

**Comment by deadprogram** [comment] 2017-10-27 07:46
Hello @jcbritobr sounds like you are using Visual Studio code. I suggest setting the autobuild setting to false, as discussed here: https://github.com/Microsoft/vscode-go/issues/696#issuecomment-270525104

The problem is that building the cgo code takes more time, hence the slowdown. Try setting `"go.gocodeAutoBuild": false` in your vscode settings.

Hope that helps!

**Comment by jcbritobr** [comment] 2017-10-27 08:59
Hi @deadprogram, good morning,

Setting "go.gocodeAutoBuild": false doesn't work. When you type any function of package, the cc1plus got high cpu and memory usage. Also the entire intellisense stop working. I will see if i fill a bug in vscode bug tracking, proper golang page:

Here is a cpu  timeline snapshot of my machine:
![screenshot_20171027_065236](https://user-images.githubusercontent.com/6579862/32096154-4d0645e8-bae4-11e7-88fd-27ba31e4ee0c.png)

**Comment by deadprogram** [comment] 2017-10-27 09:02
This seems like an VS.CODE editor problem with Go packages that use cgo extensively, not something to do with GoCV itself. You might need to restart your editor, or ? I'm not really sure how to help you here.

**Comment by jcbritobr** [comment] 2017-10-27 11:41
Yes. I post only as a warning to this issue with gocode tooling. I will fill a bug in vscode or go tooling page, and use gocv with kate. Thank you for answare. Nice work with this package.

**Comment by deadprogram** [comment] 2017-10-27 11:52
I appreciate you posting, since I actually was wondering why my own machine was doing this when editing code. I have almost exactly the same config as you do, VS code on Linux. 

However my performance slowdown kicks in only occasionally, and it was when I make changes to the package itself, waiting for the updated golang tooling to update my workspace's "Problems" pane. When I turned off that setting, seems like have not had that problem. I was just examining my system monitor as well, and I did not see the spike you referred to.

**Comment by deadprogram** [comment] 2018-01-10 14:42
I have a new machine and just installed the latest vscode. Seems like it is working more efficiently now? Perhaps it is my faster processor. Anyone else have any comments?

**Comment by deadprogram** [comment] 2018-01-21 10:43
If you are consuming GoCV and not modifying it, using the `go install` instructions provided by @directive-cary in https://github.com/hybridgroup/gocv/pull/63 addresses this. I will close this issue once the next release goes out.

**Comment by deadprogram** [comment] 2018-01-23 17:36
These docs were released as part of v0.8.0 so now closing. Thanks again!

**Closed by deadprogram** 2018-01-23 17:36 UTC
Labels: documentation
